---
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "s-ui"
    volumes:
      - /root/s-ui/db:/app/db
      - /root/s-ui/cert:/app/cert
    tty: true
    restart: unless-stopped
    network_mode: host
  
